-- Table: public.appointments
CREATE TABLE IF NOT EXISTS public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  appointment_time timestamp with time zone NOT NULL,
  pet_name text NOT NULL,
  owner_name text NOT NULL,
  whatsapp text NOT NULL,
  service text NOT NULL,
  weight text NOT NULL,
  addons text[],
  price numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  pet_breed text,
  owner_address text,
  monthly_client_id uuid,
  condominium text,
  extra_services jsonb,
  observation text,
  responsible text,
  PRIMARY KEY (id)
);

-- Table: public.pets
CREATE TABLE IF NOT EXISTS public.pets (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  breed text NOT NULL,
  service text NOT NULL,
  before_image_url text NOT NULL,
  after_image_url text NOT NULL,
  PRIMARY KEY (id)
);

-- Table: public.monthly_clients
CREATE TABLE IF NOT EXISTS public.monthly_clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  pet_name text NOT NULL,
  pet_breed text,
  owner_name text NOT NULL,
  owner_address text,
  whatsapp text NOT NULL,
  service text NOT NULL,
  weight text NOT NULL,
  price numeric NOT NULL,
  recurrence_type text NOT NULL,
  recurrence_day integer NOT NULL,
  recurrence_time integer NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  payment_status text NOT NULL DEFAULT 'Pendente'::text,
  payment_due_date date,
  condominium text,
  extra_services jsonb,
  pet_photo_url text,
  excluded_dates text[] DEFAULT '{}'::text[],
  PRIMARY KEY (id)
);

-- Table: public.clients
CREATE TABLE IF NOT EXISTS public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  phone text,
  PRIMARY KEY (id)
);

-- Table: public.controle_bloqueio_chat
CREATE TABLE IF NOT EXISTS public.controle_bloqueio_chat (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  telefone character varying UNIQUE,
  bloqueado_em timestamp without time zone,
  expira_em timestamp without time zone,
  PRIMARY KEY (id)
);

-- Table: public.daycare_enrollments
CREATE TABLE IF NOT EXISTS public.daycare_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  pet_name text NOT NULL,
  pet_breed text,
  is_neutered boolean,
  pet_sex text,
  pet_age text,
  has_sibling_discount boolean,
  tutor_name text NOT NULL,
  tutor_rg text,
  address text NOT NULL,
  contact_phone text NOT NULL,
  emergency_contact_name text,
  emergency_contact_phone text,
  vet_phone text,
  gets_along_with_others boolean,
  last_vaccine text,
  last_deworming text,
  last_flea_remedy text,
  has_allergies boolean,
  allergies_description text,
  needs_special_care boolean,
  special_care_description text,
  delivered_items jsonb,
  contracted_plan text,
  total_price numeric,
  payment_date date,
  status text NOT NULL DEFAULT 'Pendente'::text,
  extra_services jsonb,
  pet_photo_url text,
  check_in_date date,
  check_in_time time without time zone,
  check_out_date date,
  check_out_time time without time zone,
  attendance_days int4[],
  enrollment_date date,
  payment_status text NOT NULL DEFAULT 'Pendente'::text,
  PRIMARY KEY (id)
);

-- Table: public.pet_movel_appointments
CREATE TABLE IF NOT EXISTS public.pet_movel_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  appointment_time timestamp with time zone NOT NULL,
  pet_name text NOT NULL,
  pet_breed text,
  owner_name text NOT NULL,
  owner_address text,
  condominium text,
  whatsapp text NOT NULL,
  service text NOT NULL,
  weight text NOT NULL,
  addons text[],
  price numeric,
  status text DEFAULT 'AGENDADO'::text,
  monthly_client_id uuid,
  extra_services jsonb,
  observation text,
  address text,
  condo text,
  responsible text,
  PRIMARY KEY (id)
);

-- Table: public.feriados
CREATE TABLE IF NOT EXISTS public.feriados (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  data date NOT NULL,
  nome text NOT NULL,
  PRIMARY KEY (id)
);

-- Table: public.hotel_registrations
CREATE TABLE IF NOT EXISTS public.hotel_registrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pet_name text NOT NULL,
  pet_sex text CHECK (pet_sex = ANY (ARRAY['Macho'::text, 'Fêmea'::text])),
  pet_breed text,
  is_neutered boolean,
  pet_age text,
  tutor_name text NOT NULL,
  tutor_rg text,
  tutor_address text,
  tutor_phone text NOT NULL,
  tutor_email text,
  tutor_social_media text,
  vet_phone text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relation text,
  has_rg_document boolean DEFAULT false,
  has_residence_proof boolean DEFAULT false,
  has_vaccination_card boolean DEFAULT false,
  has_vet_certificate boolean DEFAULT false,
  has_flea_tick_remedy boolean DEFAULT false,
  flea_tick_remedy_date date,
  photo_authorization boolean DEFAULT false,
  retrieve_at_checkout boolean DEFAULT false,
  preexisting_disease text,
  allergies text,
  behavior text,
  fears_traumas text,
  wounds_marks text,
  food_brand text,
  food_quantity text,
  feeding_frequency text,
  accepts_treats text,
  special_food_care text,
  check_in_date date,
  check_in_time time without time zone,
  check_out_date date,
  check_out_time time without time zone,
  service_bath boolean DEFAULT false,
  service_transport boolean DEFAULT false,
  service_daily_rate boolean DEFAULT false,
  service_extra_hour boolean DEFAULT false,
  service_vet boolean DEFAULT false,
  service_training boolean DEFAULT false,
  total_services_price numeric,
  additional_info text,
  professional_name text,
  registration_date date,
  tutor_check_in_signature text,
  tutor_check_out_signature text,
  declaration_accepted boolean DEFAULT false,
  status text DEFAULT 'Ativo'::text CHECK (status = ANY (ARRAY['Ativo'::text, 'Concluído'::text, 'Cancelado'::text])),
  checked_in_at timestamp without time zone,
  checked_out_at timestamp without time zone,
  check_in_status character varying DEFAULT 'pending'::character varying CHECK (check_in_status::text = ANY (ARRAY['pending'::character varying, 'checked_in'::character varying, 'checked_out'::character varying]::text[])),
  extra_services jsonb,
  food_observations text,
  tutor_signature text,
  veterinarian text,
  responsible_signature text,
  approval_status text DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approval_observation text,
  pet_weight text,
  contract_accepted boolean DEFAULT false,
  last_vaccination_date date,
  pet_photo_url text,
  payment_status text DEFAULT 'Pendente'::text,
  PRIMARY KEY (id)
);

-- Table: public.notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  type character varying NOT NULL,
  data jsonb NOT NULL,
  read boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: public.daycare_diary_entries
CREATE TABLE IF NOT EXISTS public.daycare_diary_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL,
  date date NOT NULL,
  mood text CHECK (mood = ANY (ARRAY['Animado'::text, 'Normal'::text, 'Sonolento'::text, 'Agitado'::text])),
  behavior integer CHECK (behavior >= 1 AND behavior <= 5),
  social_outros boolean DEFAULT false,
  social_descanso boolean DEFAULT false,
  social_quieto boolean DEFAULT false,
  feeding text CHECK (feeding = ANY (ARRAY['Comeu tudo'::text, 'Comeu pouco'::text, 'Não comeu'::text])),
  needs_logs jsonb DEFAULT '[]'::jsonb,
  obs text,
  media_urls text[] DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  social_notes jsonb DEFAULT '[]'::jsonb,
  emotional_notes jsonb DEFAULT '[]'::jsonb,
  PRIMARY KEY (id)
);

-- Table: public.disabled_dates
CREATE TABLE IF NOT EXISTS public.disabled_dates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  service text NOT NULL CHECK (service = ANY (ARRAY['BATH_GROOM'::text, 'PET_MOVEL'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

-- Table: public.service_prices
CREATE TABLE IF NOT EXISTS public.service_prices (
  weight_category text NOT NULL,
  bath_price numeric NOT NULL,
  bath_and_grooming_price numeric NOT NULL,
  grooming_only_price numeric NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (weight_category)
);

-- Foreign Keys
ALTER TABLE public.appointments
  ADD CONSTRAINT appointments_monthly_client_id_fkey FOREIGN KEY (monthly_client_id) REFERENCES public.monthly_clients (id) ON DELETE CASCADE;

ALTER TABLE public.pet_movel_appointments
  ADD CONSTRAINT pet_movel_appointments_monthly_client_id_fkey FOREIGN KEY (monthly_client_id) REFERENCES public.monthly_clients (id) ON DELETE CASCADE;

ALTER TABLE public.daycare_diary_entries
  ADD CONSTRAINT daycare_diary_entries_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.daycare_enrollments (id) ON DELETE CASCADE;

-- Remember to re-configure RLS Policies manually in the new project dashboard for full security.
